[package]
name = "paimon-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "paimon_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
paimon = { path = "../../../rust-projects/paimon-rust/crates/paimon" }
tokio = { version = "1.39", features = ["full"] }
arrow-array = "55"
arrow-schema = "55"
arrow = { version = "55", features = ["ffi"] }
futures-util = "0.3"

[profile.release]
opt-level = 3
lto = true

